name: Repsy Landing Staging Deploy

on:
    push:
        branches:
            - staging

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: 'staging'

        steps:
            - name: Checkout to the staging branch
              uses: actions/checkout@v2

            - name: Setup kubectl
              uses: azure/setup-kubectl@v1

            - name: Compile
              run: bash ./compile.sh

            - name: Create the image tag
              run: echo "tag=staging-$(date '+%y%m%d%H%M')" >> $GITHUB_ENV

            - name: Build the image
              run: bash ./package.sh ${{ env.tag }}

            - name: Deploy to the kubernetes
              env:
                  DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
                  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
                  K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
              run: bash ./deploy.sh ${{ env.tag }}
