name: Repsy Landing Production Deploy

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: 'prod'

        steps:
            - name: Checkout to the main branch
              uses: actions/checkout@v2

            - name: Setup kubectl
              uses: azure/setup-kubectl@v1

            - name: Compile
              run: bash ./compile.sh

            - name: Create the image tag
              run: echo "tag=prod-$(date '+%y%m%d%H%M')" >> $GITHUB_ENV

            - name: Build the image
              env:
                  DOCKER_HUB_LOGIN: ${{ secrets.DOCKER_HUB_LOGIN }}
                  DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}
              run: bash ./package.sh ${{ env.tag }}

            - name: Deploy to the kubernetes
              env:
                  K8S_CONFIG: ${{ secrets.K8S_CONFIG }}
              run: bash ./deploy.sh ${{ env.tag }}
